name: Half-year calendar

on:
 schedule:
   - cron: "0 0 * * *" 
 workflow_dispatch:
 push:
   branches:
     - main
     
jobs:
 generate:
   permissions:
     contents: write
   runs-on: ubuntu-latest
   timeout-minutes: 5

steps:
     # Checkout the repository
     - name: Checkout repository
       uses: actions/checkout@v3

     # Generate basic profile
     - name: Generate basic profile
       uses: lowlighter/metrics@latest
       with:
         filename: basicprofile.plugin.classic.svg
         token: ${{ secrets.METRICS_TOKEN }}
         template: classic
         base: header, activity, community, repositories, metadata
         config_timezone: America/Bogota
         plugin_introduction: yes
         plugin_introduction_title: yes
         plugin_stargazers: yes   

     # Generate full calendar
     - name: Generate half-year calendar
       uses: lowlighter/metrics@latest
       with:
         filename: calendar.plugin.fullyear.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_isocalendar: yes
         plugin_isocalendar_duration: full-year

      # Generate Lenguage activity
     - name: Generate half-year calendar
       uses: lowlighter/metrics@latest
       with:
         filename: calendar.plugin.fullyear.svg
         token: ${{ secrets.METRICS_TOKEN }}
         base: ""
         plugin_languages: yes
         plugin_languages_analysis_timeout: 15
         plugin_languages_sections: recently-used
         plugin_languages_colors: github
         plugin_languages_limit: 8
      


